"use client";
import { Outfit } from 'next/font/google';
import './globals.css';
// components
import Header from '@/components/Header';
import Footer from '@/components/Footer';
// theme provider
import { ThemeProvider } from '@/components/ThemeProvider';
import { Toaster, toast } from 'sonner';

const outfit = Outfit({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Patrick Becker\'s Portfolio',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  return (
     
    
    <html lang='en' suppressHydrationWarning>
      <link rel="icon" href="/public/pb-favicon.ico" size='any' />
      <body className={outfit.className}>
        <ThemeProvider attribute='class' defaultTheme='light'>
          <Header />
          {children}
          <Toaster 
            position='bottom-center'
            richColors />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
